In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
#One-hot representation using list comprehension
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9316, 6867, 9597, 4588],
 [9316, 6867, 9597, 4372],
 [9316, 8449, 9597, 4096],
 [2041, 3550, 917, 4338, 8682],
 [2041, 3550, 917, 4338, 521],
 [7337, 9316, 2472, 9597, 4527],
 [805, 9120, 9538, 4338]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
#set max sentence length for simple RNN
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)


[[   0    0    0    0 9316 6867 9597 4588]
 [   0    0    0    0 9316 6867 9597 4372]
 [   0    0    0    0 9316 8449 9597 4096]
 [   0    0    0 2041 3550  917 4338 8682]
 [   0    0    0 2041 3550  917 4338  521]
 [   0    0    0 7337 9316 2472 9597 4527]
 [   0    0    0    0  805 9120 9538 4338]]


In [10]:
## feature representation
dim=10

In [11]:
#Creating embedded layer for model and train it
# Define model
model = Sequential()
model.add(Embedding(voc_size,dim,input_length = sent_length))  # No need for input_length
model.compile('adam','mse')


c:\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
#predict the embedding words
model.predict(embedded_docs)

InvalidArgumentError: Graph execution error:

Detected at node sequential_2_1/embedding_2_1/GatherV2 defined at (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py", line 18, in <module>

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\traitlets\config\application.py", line 1075, in launch_instance

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelapp.py", line 739, in start

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\tornado\platform\asyncio.py", line 205, in start

  File "c:\Python312\Lib\asyncio\base_events.py", line 639, in run_forever

  File "c:\Python312\Lib\asyncio\base_events.py", line 1985, in _run_once

  File "c:\Python312\Lib\asyncio\events.py", line 88, in _run

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelbase.py", line 534, in process_one

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\ipykernel\ipkernel.py", line 362, in execute_request

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelbase.py", line 778, in execute_request

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\ipykernel\ipkernel.py", line 449, in do_execute

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\ipykernel\zmqshell.py", line 549, in run_cell

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code

  File "C:\Users\nrageswari\AppData\Local\Temp\ipykernel_10544\1706915757.py", line 2, in <module>

  File "c:\Python312\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "c:\Python312\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 559, in predict

  File "c:\Python312\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 256, in one_step_on_data_distributed

  File "c:\Python312\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 246, in one_step_on_data

  File "c:\Python312\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 101, in predict_step

  File "c:\Python312\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "c:\Python312\Lib\site-packages\keras\src\layers\layer.py", line 899, in __call__

  File "c:\Python312\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "c:\Python312\Lib\site-packages\keras\src\ops\operation.py", line 46, in __call__

  File "c:\Python312\Lib\site-packages\keras\src\utils\traceback_utils.py", line 156, in error_handler

  File "c:\Python312\Lib\site-packages\keras\src\models\sequential.py", line 213, in call

  File "c:\Python312\Lib\site-packages\keras\src\models\functional.py", line 182, in call

  File "c:\Python312\Lib\site-packages\keras\src\ops\function.py", line 171, in _run_through_graph

  File "c:\Python312\Lib\site-packages\keras\src\models\functional.py", line 632, in call

  File "c:\Python312\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "c:\Python312\Lib\site-packages\keras\src\layers\layer.py", line 899, in __call__

  File "c:\Python312\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "c:\Python312\Lib\site-packages\keras\src\ops\operation.py", line 46, in __call__

  File "c:\Python312\Lib\site-packages\keras\src\utils\traceback_utils.py", line 156, in error_handler

  File "c:\Python312\Lib\site-packages\keras\src\layers\core\embedding.py", line 140, in call

  File "c:\Python312\Lib\site-packages\keras\src\ops\numpy.py", line 5239, in take

  File "c:\Python312\Lib\site-packages\keras\src\backend\tensorflow\numpy.py", line 2063, in take

indices[0,4] = 9316 is not in [0, 5000)
	 [[{{node sequential_2_1/embedding_2_1/GatherV2}}]] [Op:__inference_one_step_on_data_distributed_192]

In [15]:
#predict the first sentence
embedded_docs[0]

array([   0,    0,    0,    0, 6859, 5732,  816, 6205])

In [16]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None

In [17]:
import numpy as np

# Expand dimensions to add a batch size of 1
input_data = np.expand_dims(embedded_docs[0], axis=0)

# Predict using the model
output = model.predict(input_data)
print(output)


InvalidArgumentError: Graph execution error:

Detected at node sequential_2_1/embedding_2_1/GatherV2 defined at (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py", line 18, in <module>

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\traitlets\config\application.py", line 1075, in launch_instance

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelapp.py", line 739, in start

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\tornado\platform\asyncio.py", line 205, in start

  File "c:\Python312\Lib\asyncio\base_events.py", line 639, in run_forever

  File "c:\Python312\Lib\asyncio\base_events.py", line 1985, in _run_once

  File "c:\Python312\Lib\asyncio\events.py", line 88, in _run

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelbase.py", line 534, in process_one

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\ipykernel\ipkernel.py", line 362, in execute_request

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelbase.py", line 778, in execute_request

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\ipykernel\ipkernel.py", line 449, in do_execute

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\ipykernel\zmqshell.py", line 549, in run_cell

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes

  File "C:\Users\nrageswari\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code

  File "C:\Users\nrageswari\AppData\Local\Temp\ipykernel_10544\1335612817.py", line 7, in <module>

  File "c:\Python312\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "c:\Python312\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 559, in predict

  File "c:\Python312\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 256, in one_step_on_data_distributed

  File "c:\Python312\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 246, in one_step_on_data

  File "c:\Python312\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 101, in predict_step

  File "c:\Python312\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "c:\Python312\Lib\site-packages\keras\src\layers\layer.py", line 899, in __call__

  File "c:\Python312\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "c:\Python312\Lib\site-packages\keras\src\ops\operation.py", line 46, in __call__

  File "c:\Python312\Lib\site-packages\keras\src\utils\traceback_utils.py", line 156, in error_handler

  File "c:\Python312\Lib\site-packages\keras\src\models\sequential.py", line 213, in call

  File "c:\Python312\Lib\site-packages\keras\src\models\functional.py", line 182, in call

  File "c:\Python312\Lib\site-packages\keras\src\ops\function.py", line 171, in _run_through_graph

  File "c:\Python312\Lib\site-packages\keras\src\models\functional.py", line 632, in call

  File "c:\Python312\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "c:\Python312\Lib\site-packages\keras\src\layers\layer.py", line 899, in __call__

  File "c:\Python312\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "c:\Python312\Lib\site-packages\keras\src\ops\operation.py", line 46, in __call__

  File "c:\Python312\Lib\site-packages\keras\src\utils\traceback_utils.py", line 156, in error_handler

  File "c:\Python312\Lib\site-packages\keras\src\layers\core\embedding.py", line 140, in call

  File "c:\Python312\Lib\site-packages\keras\src\ops\numpy.py", line 5239, in take

  File "c:\Python312\Lib\site-packages\keras\src\backend\tensorflow\numpy.py", line 2063, in take

indices[0,4] = 9316 is not in [0, 5000)
	 [[{{node sequential_2_1/embedding_2_1/GatherV2}}]] [Op:__inference_one_step_on_data_distributed_263]